jetlinks-components/dashboard-component/src/main/java/org/jetlinks/community/dashboard/MeasurementParameter.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/service/DefaultElasticSearchService.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/service/ElasticSearchService.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/service/reactive/ReactiveElasticSearchService.java
jetlinks-components/gateway-component/src/main/java/org/jetlinks/community/gateway/supports/DefaultDeviceGatewayManager.java
jetlinks-components/gateway-component/src/main/java/org/jetlinks/community/gateway/supports/DeviceGatewayProperties.java
jetlinks-components/gateway-component/src/main/java/org/jetlinks/community/gateway/supports/DeviceGatewayPropertiesManager.java
jetlinks-components/gateway-component/src/main/java/org/jetlinks/community/gateway/supports/DeviceGatewayProvider.java
jetlinks-components/network-component/network-core/src/main/java/org/jetlinks/community/network/DefaultNetworkManager.java
jetlinks-components/network-component/network-core/src/main/java/org/jetlinks/community/network/NetworkManager.java
jetlinks-components/network-component/network-core/src/main/java/org/jetlinks/community/network/utils/DeviceGatewayHelper.java
jetlinks-components/network-component/tcp-component/src/main/java/org/jetlinks/community/network/tcp/device/TcpServerDeviceGateway.java
jetlinks-components/network-component/tcp-component/src/main/java/org/jetlinks/community/network/tcp/device/TcpServerDeviceGatewayProvider.java
jetlinks-components/network-component/tcp-component/src/main/java/org/jetlinks/community/network/tcp/server/TcpServer.java
jetlinks-components/timeseries-component/src/main/java/org/jetlinks/community/timeseries/TimeSeriesData.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/message/DeviceMessageConnector.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/message/writer/TimeSeriesMessageWriterConnector.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/AbstractDeviceDataStoragePolicy.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/DefaultDeviceDataService.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/TimeSeriesColumnDeviceDataStoragePolicy.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/TimeSeriesDeviceDataStoragePolicy.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/TimeSeriesRowDeviceDataStoreStoragePolicy.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/timeseries/DeviceTimeSeriesMetric.java
jetlinks-manager/network-manager/src/main/java/org/jetlinks/community/network/manager/service/DeviceGatewayConfigService.java

docs(数据流【设备网关-->物模型转换->时序入库】): 增加数据流入库的代码注释 优化代码结构

增加数据流入库的代码注释 

---

jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/index/strategies/TimeByDayElasticSearchIndexStrategy.java

按日期来划分索引策略

---

jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/web/MenuController.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/web/PermissionController.java

fix(接口缺失): 添加菜单和权限数据验证接口

---

jetlinks-components/notify-component/notify-sms/src/main/java/org/jetlinks/community/notify/sms/aliyun/AliyunSmsNotifier.java
jetlinks-components/notify-component/notify-sms/src/main/java/org/jetlinks/community/notify/sms/aliyun/web/AliyunSmsController.java

fix(阿里云短信): 解决短信模板和标签只能查询第一页数据问题

fix(阿里云短信): 解决短信模板和标签只能查询第一页数据问题

---

jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/term/DeviceCategoryTerm.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/term/DeviceInstanceTerm.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/term/DeviceProductInfoTermBuilder.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/term/DeviceProtocolTerm.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/term/DeviceTypeTerm.java

feat(查询条件): 添加设备查询条件构造器

---

jetlinks-components/gateway-component/src/main/java/org/jetlinks/community/gateway/supports/DeviceGatewayProperties.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/DefaultDeviceConfigMetadataManager.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/DefaultDeviceConfigMetadataSupplier.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/DeviceConfigMetadataManager.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/spi/DeviceConfigMetadataSupplier.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/DeviceProductController.java

feat(产品): 根据指定的接入方式获取产品需要的配置定义

feat(产品): 根据指定的接入方式获取产品需要的配置定义

---

jetlinks-components/network-component/http-component/src/main/java/org/jetlinks/community/network/http/server/vertx/DefaultHttpServerProvider.java
jetlinks-components/network-component/mqtt-component/src/main/java/org/jetlinks/community/network/mqtt/client/MqttClientProvider.java

fix(网络组件): 设置支持路由设置类型的网络组件可以被复用

fix(网络组件): 设置支持路由设置类型的网络组件可以被复用

---

docker/run-all/docker-compose.yml

fix(docker镜像版本): 修改前端镜像版本

---

jetlinks-components/notify-component/notify-sms/src/main/java/org/jetlinks/community/notify/sms/aliyun/AliyunSmsTemplate.java

修复通过场景联动发送阿里云短信失败问题

---

jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/service/data/DeviceDataService.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/DeviceInstanceController.java

fix(设备管理): 添加post方式的设备属性列表查询接口

fix(设备管理): 添加post方式的设备属性列表查询接口

---

README.md

fix(READEME): 修改产品文地址

---

jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/configuration/CustomAuthenticationConfiguration.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/configuration/UserEntityTypeJSONDeserializer.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/entity/UserDetail.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/enums/DefaultUserEntityType.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/enums/UndefinedUserEntityType.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/enums/UserEntityType.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/enums/UserEntityTypes.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/service/UserDetailService.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/web/WebFluxUserController.java

fix(用户管理): 解决用户管理类型不存在问题

---

jetlinks-components/common-component/src/main/java/org/jetlinks/community/config/verification/ConfigVerificationService.java

fix(系统配置):解决base-path校验可能失效问题

---

README.md

fix(文档):修复文案跳转链接错误

---

README.md

feat(服务支持): 添加JetLinks服务器支持说明

---

jetlinks-manager/rule-engine-manager/src/main/java/org/jetlinks/community/rule/engine/entity/AlarmRuleBindEntity.java

doc(告警模块): 修改有歧义的字段描述

---

pom.xml

jetlinks.version:1.2.2-SNAPSHOT
easyorm.version:4.1.2-SNAPSHOT
hsweb.framework.version: 4.0.17-SNAPSHOT

build: 升级 jetlinks core,easyorm,hsweb 依赖版本

---

README.md

feat(联系方式): 添加qq群5联系方式

---

jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/parser/DefaultLinkTypeParser.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/parser/LinkTypeParser.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/parser/TermsHandler.java
jetlinks-components/elasticsearch-component/src/main/java/org/jetlinks/community/elastic/search/utils/QueryParamTranslator.java

fix(ES查询): 解决动态terms条件转ES查询条件错误问题

fix(ES查询): 解决动态terms条件转ES查询条件错误问题

---

jetlinks-components/common-component/src/main/java/org/jetlinks/community/utils/ReactorUtils.java

fix: 修复并完善ReactorUtils.limit()方法

---

jetlinks-manager/rule-engine-manager/src/main/java/org/jetlinks/community/rule/engine/service/terms/RuleBindAlarmTerm.java
jetlinks-manager/rule-engine-manager/src/main/java/org/jetlinks/community/rule/engine/web/AlarmHistoryController.java

fix(告警记录): 添加通过告警配置Id查询告警日志接口

---

jetlinks-manager/rule-engine-manager/src/main/resources/i18n/rule-engine-manager/messages_en.properties
jetlinks-manager/rule-engine-manager/src/main/resources/i18n/rule-engine-manager/messages_zh.properties

fix(场景联动): 修复场景联动中设备属性翻译问题

---

jetlinks-components/network-component/mqtt-component/src/main/java/org/jetlinks/community/network/mqtt/server/vertx/DefaultVertxMqttServerProvider.java

refactor: 移除重复代码

---

jetlinks-components/notify-component/notify-email/src/main/java/org/jetlinks/community/notify/email/embedded/DefaultEmailNotifier.java
jetlinks-components/notify-component/notify-email/src/main/resources/i18n/messages_en.properties
jetlinks-components/notify-component/notify-email/src/main/resources/i18n/messages_zh.properties

fix(邮件通知): 优化获取邮件附件，过大时的抛错国际化

---

jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/entity/MenuBindEntity.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/service/MenuGrantService.java
jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/web/MenuController.java

feat(菜单管理): 新增清空菜单授权功能

---

jetlinks-components/io-component/src/main/java/org/jetlinks/community/io/utils/FileUtils.java
jetlinks-components/io-component/src/main/java/org/jetlinks/community/io/utils/UrlCodecUtils.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/DeviceInstanceController.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/excel/DeviceExcelConstants.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/excel/PropertyMetadataExcelImportInfo.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/excel/PropertyMetadataImportWrapper.java

feat(设备管理): 增加解析文件为属性物模型功能

---

docker/run-all/docker-compose.yml

feat(docker镜像配置): 修改docker镜像版本

feat(docker镜像配置): 修改docker镜像版本

---

jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/function/DevicePropertyTimeFunction.java

feat(设备管理): 新增在reactorQL中获取设备属性上报时间

---

jetlinks-components/tdengine-component/src/main/java/org/jetlinks/community/tdengine/things/TDengineColumnModeSaveOperations.java
jetlinks-components/tdengine-component/src/main/java/org/jetlinks/community/tdengine/things/TDengineRowModeSaveOperations.java
jetlinks-components/things-component/src/main/java/org/jetlinks/community/things/data/operations/AbstractSaveOperations.java
jetlinks-components/things-component/src/main/java/org/jetlinks/community/things/data/operations/DataSettings.java
jetlinks-components/things-component/src/main/java/org/jetlinks/community/things/data/operations/MetricBuilder.java

fix(存储策略): 涛思数据库存储使用无模式写入创建表缺失messageId列（2.2分支）

fix(存储策略): 涛思数据库存储使用无模式写入创建表缺失messageId列

---

jetlinks-components/notify-component/notify-voice/src/main/java/org/jetlinks/community/notify/voice/aliyun/AliyunVoiceNotifier.java

fix(基础模块): 修复阿里云语音仅拨打一个用户号码的问题

---

README.md

feat(readme): 添加新QQ群信息

---

jetlinks-components/common-component/src/main/java/org/jetlinks/community/annotation/command/CommandService.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/CommandSupportManagerProvider.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/CommandSupportManagerProviders.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/CompositeCommandSupportManagerProvider.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/InternalSdkServices.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/register/CommandServiceEndpointRegister.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/command/register/SpringBeanCommandSupportProvider.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/configuration/CommonConfiguration.java
jetlinks-components/common-component/src/main/java/org/jetlinks/community/web/CommandInfoController.java

可使用 CommandSupportManagerProviders相关方法来执行服务命令进行解耦.

feat(基础模块): 增加命令模式支持

---

jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/service/PasswordStrengthValidator.java

feat(auth): 增加密码校验功能

---

jetlinks-manager/authentication-manager/src/main/java/org/jetlinks/community/auth/service/OrganizationService.java
jetlinks-manager/device-manager/src/main/java/org/jetlinks/community/device/web/DeviceProductController.java

fix(auth): 修复组织父节点清除失败问题

---

jetlinks-manager/rule-engine-manager/src/main/java/org/jetlinks/community/rule/engine/scene/SceneUtils.java
jetlinks-manager/rule-engine-manager/src/main/java/org/jetlinks/community/rule/engine/scene/Variable.java

fix(场景联动): 修复执行动作的内置参数获取可能失效的问题
